In [2]:
import numpy as np

In [11]:
a=np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [12]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [13]:
a.ndim

1

In [14]:
a.shape

(3,)

In [15]:
a.dtype

dtype('int16')

In [17]:
a.itemsize
b.itemsize

8

In [18]:
b.nbytes

48

# Accessin/changing specific elements, rows, columns,etc

In [19]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


# Get spesific element

In [20]:
a[1,5]

13

In [21]:
### Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
### Get specific column
a[:,2]

array([ 3, 10])

In [23]:
### Getting a little more fancy[startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [24]:
a[1,5]=2
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12  2 14]]


In [25]:
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12  2 14]]


In [27]:
#3D example
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
#Get specific element(work outside in)
b[0,1,1]


4

In [30]:
#replace
b[:,1,:]=[[9,9],[8,8]]

In [31]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initializing different types of arrays

In [33]:
# All zeros matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
#All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [37]:
# Any other number 
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [38]:
#Any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [43]:
# Random decimal numbers
np.random.rand(4,2,3)

array([[[0.77382228, 0.23161356, 0.73969251],
        [0.34155108, 0.72561247, 0.04491743]],

       [[0.55764923, 0.72376058, 0.17522417],
        [0.36145378, 0.12738526, 0.82779855]],

       [[0.75981509, 0.06660125, 0.42322036],
        [0.05876124, 0.95791221, 0.62732233]],

       [[0.80946324, 0.83367546, 0.9799912 ],
        [0.70044186, 0.96204117, 0.54898091]]])

In [49]:
np.random.randint(2,7, size=(3,3))

array([[3, 6, 4],
       [2, 5, 4],
       [6, 3, 2]])

In [ ]:
# The identity matrix
np.identity(5)

In [55]:
#repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [59]:
output=np.ones((5,5))
print(output)
z=np.zeros((3,3))
z[1,1]=9
print(z)
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [60]:
# Be careful when copying array

In [62]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)

[1 2 3]


# Masthematics

In [3]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
a+2

array([3, 4, 5, 6])

In [5]:
a-2

array([-1,  0,  1,  2])

In [6]:
a*2

array([2, 4, 6, 8])

In [7]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [8]:
b=np.array([1,0,1,0])

In [9]:
a+b

array([2, 2, 4, 4])

In [10]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [13]:
#Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# Linear algebra

In [14]:
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [16]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [17]:
# Find the determinent 
c=np.identity(3)
np.linalg.det(c)

1.0

#### Statistics

In [44]:
stats=np.array([[1,2,3],[4,5,6]])
stats
print(stats)

[[1 2 3]
 [4 5 6]]


In [19]:
np.min(stats)

1

In [47]:
np.max(stats,axis=1)

array([3, 6])

In [21]:
np.sum(stats)

21

In [22]:
np.sum(stats,axis=0)

array([5, 7, 9])

### Reorganizing the array

In [24]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [25]:
after=before.reshape((2,2,2))

In [26]:
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
# Vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [29]:
#Horizontal stack
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
h1=np.ones((2,4))
h2=np.zeros((2,2))
h2
np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous

### Load Data from File

In [59]:
filedata=np.genfromtxt('data.txt', delimiter=',')
filedata=filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced indexing

In [74]:
#np.any(filedata>50,axis=1)
(~((filedata>50) & (filedata<100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [78]:
np.all(filedata>50,axis=1)

array([False, False, False])

In [39]:
## Ypu can index a list in a NumPY
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])